/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vv_ndk_Hi */

#ifndef _Included_com_vv_ndk_Hi
#define _Included_com_vv_ndk_Hi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vv_ndk_Hi
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vv_ndk_Hi_sayHi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
